format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_legato}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: LeGPUConnected}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: 'true'}
  - type: String
    attributes: {id: driverInitName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: lcdcDisplayDriver}
  - type: Menu
    attributes: {id: rtosMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: le_gfx_driver_lcdc}
  - type: DirectDependency
    attributes: {id: gpu_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_gfx2d}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: LE GPU Driver}
- type: ElementPosition
  attributes: {x: '634', y: '420', id: gfx_legato}
